# Generated by Django 3.2.9 on 2021-12-05 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibilityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Default', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Группа ответственности',
                'verbose_name_plural': 'Группы ответственности',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Название')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Название')),
                ('Type', models.CharField(choices=[('Инцедент', 'Инцедент'), ('Запрос на обслуживание', 'Запрос на обслуживание')], max_length=30, verbose_name='Тип')),
                ('Сomplexity', models.IntegerField(verbose_name='Сложность')),
                ('ReactionTime', models.DurationField(verbose_name='Время реакции,ч')),
                ('TimeOfExecution', models.DurationField(verbose_name='Время выполненияб,ч')),
                ('IDService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.service')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfCreation', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(help_text='Введите тему заявки, описывающую суть проблемы/запроса', max_length=100, verbose_name='Тема')),
                ('Сomment', models.CharField(help_text='Введите детальное описание проблемы', max_length=1000, verbose_name='Содержание заявки')),
                ('Status', models.CharField(choices=[('Новая', 'Новая'), ('В_работе', 'В работе'), ('На_проверке', 'На проверке'), ('Выполнена', 'Выполнена')], default='Новая', help_text='Выберите текущий статус заявки', max_length=30, verbose_name='Статус')),
                ('Rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Оцените работу по заявке от 1 до 5 (5 - отлично)', null=True, verbose_name='Оценка')),
                ('IDAutor', models.ForeignKey(help_text='Выберите автора заявки', on_delete=django.db.models.deletion.CASCADE, related_name='autor_requests', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('IDExecutor', models.ForeignKey(blank=True, help_text='Выберите исполнителя заявки', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_requests', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('IDResponsibilityGroup', models.ForeignKey(help_text='Выберите группу ответственности, в которую попадет заявка', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='userapp.responsibilitygroup', verbose_name='Группа ответственности')),
                ('IDWork', models.ForeignKey(help_text='Выберите вид работ, к которому относится заявка', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='userapp.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-DateOfCreation'],
                'default_related_name': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(help_text='Введите текст сообщения', max_length=1000, verbose_name='Текст сообщения')),
                ('Data', models.DateTimeField(auto_now=True)),
                ('File', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл')),
                ('Status', models.BooleanField(blank=True, default=False, help_text='Выберите статус сообщения (прочитано оно получателем или нет)', null=True, verbose_name='Статус')),
                ('IDAutor', models.ForeignKey(blank=True, help_text='Выберите автора сообщения', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autor_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('IDRecipient', models.ForeignKey(blank=True, help_text='Выберите получателя сообщения', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('IDRequest', models.ForeignKey(help_text='Выберите заявку, к которой относится сообщение', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='userapp.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('IDRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.request')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
