# Generated by Django 3.2.9 on 2022-01-05 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='DateOfComplete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='Status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('on_check', 'На проверке'), ('completed', 'Выполнена')], default='new', help_text='Выберите текущий статус заявки', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='work',
            name='IDService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='userapp.service'),
        ),
    ]
