# Generated by Django 3.2.9 on 2022-01-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20220105_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Data',
            new_name='Date',
        ),
    ]
